# 목차
* [Chapter 1 주요 개념에 대한 객관식 질문](#chapter1)
* [Chapter 2-1 긴 시퀸스 모델링의 문제점](#chapter2_1)
* [Chapter 2-2 어텐션 메커니즘으로 데이터 의존성 포착하기](#chapter2_2)
* [Chapter 2-3 셀프 어텐션으로 입력의 서로 다른 부분에 주의 기울이기](#chapter2_3)
* [Chapter 2-4 훈련 가능한 가중치를 가진 셀프 어텐션 구하기](#chapter2_3)



## Chapter 1 주요 개념에 대한 객관식 질문 <a class="anchor" id="chapter1"></a>

## Chapter 2-1 긴 시퀸스 모델링의 문제점 <a class="anchor" id="chapter2_1"></a>
1. 텍스트를 한 언어에서 다른 언어로 번역할 때 생기는 주요 문제는 무엇일까요? 단순하게 한단어씩 번역하지 못하는 이유는 무엇인가요?
   - 소스 언어와 타켓 언어의 문법 구조가 다르기 때문에 한 단어씩 번역할 수 없다.
   - 어떤 단더는 소스 문장에서 앞 단어나 뒷 단어를 참조해서 번역해야한다.

2. 언어 번역을 위한 RNN 모델의 인코더와 디코더의 역활을 설명하세요.
    - 인코더
       - 입력데이터를 받아 순차적으로 처리한다.
       - 각 단계마다 은닉상태를 업데으트 하며, 전체 입력 텍스트르 하나의 은닉 상태 벡터로 압축한다.
    - 디코더
       - 매 스텝마다 은닉상태를 업데이트 하며, 이를 통해 다음 단어 예측에 필요한 문맥 정보를 다음 스텝에 전달한다.
       - 이전에 생성된 단어와 인코더의 최종 은닉 상태를 사용하여 다음 단어를 예측한다.

3. 긴 시퀸스를 처리하는 데 인코더-디코더 RNN의 주요 제약은 무엇인가요?
   - 최종 은닉 상태에만 의존하기 때문에 긴 시퀸스의 모든 정보를 효과적으로 캡처하지 못한다.
   - 멀리 떨어진 단어에 의존성이 있는 경우 이를 포착하기 어렵다.

4. 인코더-디코더 RNN 측면에서 은닉 상태의 개념을 설명하세요.
    - 입력 시퀸스의 압축된 표현으로 전체 텍스트의 의미를 포착한다.
    - 디코더가 번역된 출력을 생성하기 위해 사용하는 메모리 셀의 역할을 한다.

## Chapter 2-2 어텐션 메커니즘으로 데이터 의존성 포착하기 <a class="anchor" id="chapter2_2"></a>
1. 긴 텍스트를 번역하는데 RNN의 주요 제약은 무엇인가요?
   - 긴 시퀸스의 모든 정보를 하나의 은닉 상태 벡터에 압축해야 하기 때문에 정보 손실이 발생한다.
    - 멀리 떨어진 단어들 간의 의존성을 포착하기 어렵다.

2. LLM에서 셀프 어텐션은 얼마나 중요한가요?
   - 셀프 어텐션은 입력 시퀸스 내의 모든 단어들 간의 관계를 모델링하여 문맥을 더 잘 이해할 수 있게 한다.
    - 이를 통해 긴 시퀸스에서도 중요한 정보에 집중할 수 있어 번역 품질이 향상된다.

3. 왼쪽의 용어와 오른쪽의 설명을 맞게 연결하세요.

    ![W-03-02-03](image/W-03-02-03.png)


## Chapter 2-3 셀프 어텐션으로 입력의 서로 다른 부분에 주의 기울이기 <a class="anchor" id="chapter2_3"></a>
1. 셀프 어텐션의 '셀프'의 의미는 무엇인가요?
    - 하나의 입력 시퀸스 내의 원소들이 서로에게 주의를 기울인다는 의미이다.
    - 하나의 입력 시퀸스에 있는 서로 다른 위치의 원소 사이에서 어텐션 가중치를 계산한다.

2. 셀프 어텐션에서 문맥 벡터의 개념을 설명하세요.
    - 입력 시퀸스에 있는 모든 원소의 정보를 통합한 고품질 임베딩 벡터
    - 다른 원소와의 관계를 고려하여 각 원소를 이해한 결과물이다.

3. 셀프 어텐션에서 어텐션 점수의 역활은 무엇인가요?
    - 입력 시퀸스에 있는 서로 다른 원소사이의 관련성을 측정한다.
    - 어텐션 점수는 각 원소 사이의 유사성을 나타내며, 이를 통해 중요한 요소에 더 많은 주의를 기울일 수 있다.

4. 어텐션 점수에 정규화를 적용하는 이유는 무엇인가요?
    - 어텐션 점수를 확률 분포로 변환하여 각 원소의 상대적 중요성을 나타내기 위해서이다.
    - 정규화를 통해 어텐션 가중치가 0과 1 사이의 값이 되도록 하여 해석하기 쉽게 만든다.

5. 다음 코드에서 1에 들어갈 함수는 무엇인가요?
    - dot

        ![W-03-03-05](image/W-03-03-05.png)

6. 셀프 어텐션에서 소프트맥스 함수의 목적은 무엇인가요?
   - 어텐션 가중치가 항상 0과 1 사이의 값이 되도록 보장한다.
   - 어텐션 점수를 확률 분포로 변환하여 각 원소의 상대적 중요성을 나타낸다.
   - 큰 입력이나 작은 입력에 대해 안정적인 계산을 가능하게 한다.

7. 다음 그름에서 각 번호가 나타내는 단계는 무엇인가요?
    - 1: 토큰 임베딩
    - 2: 어텐션 가중치 계산
    - 3: 문맥 벡터 계산

        ![W-03-03-07](image/W-03-03-07.png)

8. 어텐션 가중치를 사용해 문맥 벡터를 어떻게 계산하나요?
    - 입력 벡터와 어텐션 가중치를 곱한 후, 이를 모두 더하여 문맥 벡터를 얻는다.

9. 왼쪽의 용어와 오른쪽의 설명을 맞게 연결하세요.

    ![W-03-03-09](image/W-03-03-09.png)


## Chapter 2-4 훈련 가능한 가중치를 가진 셀프 어텐션 구현하기 <a class="anchor" id="chapter2_4"></a>
1. 셀프 어텐션 메커니즘에서 가중치 행렬 W<sub>q</sub>, W<sub>k</sub> , W<sub>v</sub>의 목적을 설명하시요
   - W_q: 입력 임베딩을 Query 공간으로 선형투영. 다른 토큰들을 '질문'할 특징을 만듭니다.
   - W_k: 입력 임베딩을 Key 공간으로 선형투영. 각 토큰의 '응답 가능한' 특징을 만듭니다.
   - W_v: 입력 임베딩을 Value 공간으로 선형투영. 최종 문맥(출력)으로 전달될 정보입니다.
   - 이 세 행렬 덕분에 모델은 어떤 특징으로 비교(유사도)할지(Q vs K)와, 비교 결과로 어떤 정보를 모아야 할지(V)를 학습할 수 있습니다.

2. 셀프 어텐션 메커니즘에서 어텐션 점수와 어텐션 가중치를 계산하는 과정을 설명하세요.
   - 훈련 가능한 가중치 행령 w_q, W_k, W_v를 생성한다.
   - 입력 벡터를 각각 쿼리, 키, 값 벡터로 선형 투형한다.
   - 입력 쿼리 벡터와 키 벡터 간의 행렬곱을 수행하여 어텐션 점수를 계산한다.
   - 소프트맥스 함수를 사용하여 어텐션 점수를 정규화하여 어텐션 가중치를 얻는다.
   - 값 벡터와 어텐션 가중치를 곱하여 문맥 벡터를 계산한다.

3. 스케일드 점곱 어텐션 메커니즘에서 임베딩 차원(d_k)의 제곱근으로 나누는 것이 왜 중요한가요?
   - 임베딩 차원이 커질수록 어텐션 점수의 분산이 커져 소프트맥스 함수가 매우 작은 기울기를 갖게 된다.
   - 이를 방지하기 위해 어텐션 점수를 d_k의 제곱근으로 나누어 안정적인 학습을 가능하게 한다.

In [5]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

attn_scores = inputs @ inputs.T
print(attn_scores)

attn_weights = torch.softmax(attn_scores, dim=1) # 1: 마지막 차원을 기준으로 정규화 진행
print(attn_weights)

all_context_vecs = attn_weights @ inputs
print("모든 문맥 벡터:\n", all_context_vecs)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
모든 문맥 벡터:
 tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
