# 파이토치 소개 목차
* [Chapter 1 파이토치란 무엇인가요?](#chapter1)
* [Chapter 2 텐서 이해하기](#chapter2)

## Chapter 1 파이토치란 무엇인가요? <a class="anchor" id="chapter1"></a>
1. 파이토치 개요
   - 오픈 소스 파이썬 기반 딥러닝 라이브러리이다.
   - 파이토치는 크게 텐서 라이브러리, 자동 미분엔진, 딥러닝 라이브러리 세 가지 주요 구성 요소를 갖는다.
      - 텐서 라이브러리: 넘파이 개념을 확장하여 GPU로 계산을 가속하하는 기징이 추된 배열 지향 프로그래밍 라이브러리
      - 자동 미분엔진: 텐서 연산에 대하 자동으로 그레이디언트를 계산할 수 있어 간단하게 역전파와 모델 최적화를 수행한다.
      - 딥러닝 라이브러리: 다양한 딥러닝 모델을 구축하고 훈련하기 위해 모듈화되어 있다.

         ![구조](image/A-01-structure2.png)

2. 딥러닝 이란
   - AI(인공지능): 사람의 지능이 필요한 작업을 수행할 수 있는 컴퓨터 시스템을 만드는 것
   - 머신러닝
      - AI의 하위 분야로, 학습 알고리즘을 개발하고 향상시키는 데 초점을 맞춘다.
      - 작업을 명시적으로 프로그래밍하지 않고도 데이터에서 학습하여 예측을 만들거나 결정을 내리도록 한다.
   - 딥러닝
      - 머신러닝의 하위 분야로, 인공 신경망을 사용하여 데이터에서 학습한다.
      - 여러 층의 신경망을 사용하여 복잡한 패턴과 표현을 학습한다.
      - 이미지 인식, 자연어 처리, 음성 인식 등 다양한 분야에서 뛰어난 성능을 발휘한다.

3. 딥러닝 학습 단계
   - 학습 알고리즘을 사용해 샘플과 레이블로 구성된 훈련 데이터셋에서 모델을 훈련한다.
      - 예) 스팸 분류기인 경우 이베일과 사람이 분류한 '스펨', '스펨 아님'레이블로 훈련 데이터 셋을 구성한다.
   - 훈련된 모델을 사용해 새로운 샘플을 예측한다.
   - 훈련 단계와 추론 단계 사이에 모델 평가를 추가하여 모델을 실전 애플리케이션에 사용되기 전에 성능을 측정한다.

      ![단계](image/A-01-step2.png)

## Chapter 2 텐서 이해하기 <a class="anchor" id="chapter2"></a>
1. 텐서는 벡터와 행렬을 더 높은 차원으로 일반화한 수학적 개념이다
   - 텐서는 차원 개수를 나타내는 차수(rank or order)로 특징이 결정되는 수학적 객체이다.

      ![텐서](image/A-02-tensor.png)

2. 계산의 측면에서 보면 텐서는 데이터 컨테이너 역할을 한다.
   - 텐서는 다차원 데이터를 담고있다.
   - 각 차원은 서로 다은 특성을 나타낸다.
      - 예) 이미지 데이터의 경우, 높이, 너비, 색상 채널이 각각 텐서의 차원을 나타낸다.
   - 이런 맥락에서 텐서 라이브러리는 배열 라이브러리의 역활을 한다.

3. 파이토치 텐서는 넘파이 배열과 비슷하지만 딥러닝에서 중요한 몇 가지 추가 기능을 가지고 있다.
   - GPU 가속: 파이토치 텐서는 GPU에서 실행될 수 있어 대규모 행렬 연산을 가속화한다.
   - 자동 미분: 파이토치 텐서는 자동 미분 기능을 제공하여 신경망의 역전파를 쉽게 구현할 수 있다.
   - 동적 계산 그래프: 파이토치는 동적 계산 그래프를 사용하여 유연한 모델 정의와 디버깅을 가능하게 한다.

4. 스칼라, 벡터, 행렬, 텐서
   - 스칼라(0차원 텐서): 단일 숫자 값
   - 벡터(1차원 텐서): 숫자의 1차원 배열
   - 행렬(2차원 텐서): 숫자의 2차원 배열
   - 고차원 텐서(3차원 이상): 3차원 이상의 배열로, 예를 들어 이미지 데이터는 (높이, 너비, 채널) 형태의 3차원 텐서로 표현된다.



In [1]:
# 파이토치 텐서 만들기
import torch

tensor0d = torch.tensor(1) # 파이썬 0차원 정수 - 스칼라 (0차원 텐서)
tensor1d = torch.tensor([1, 2, 3]) # 파이썬 1차원 리스트 - 벡터 (1차원 텐서)
tensor2d = torch.tensor([[1, 2], [3, 4]]) # 중첩된 파이썬리스트로  2차원 텐서(행렬)
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 중첩된 파이썬리스트로 3차원 텐서

5. 텐서의 데이터 타입
   - 파이토치 정수의 데이터 타입은 기본적으로 64비트를 사용한다.
   - .dtype를 통해 텐서의 데이터 타입을 확인할 수 있다.

In [2]:
tensor1d.dtype  # 텐서의 데이터 타입 확인

torch.int64

   - 파이썬 부동 소수점 숫자로 텐서를 맏르면 파이토치는 기본적으로 32비트 부동 소수점 숫자를 사용한다.

In [3]:
floatvec = torch.tensor([1.0, 2.0, 3.0])  # 파이썬 부동 소수점 숫자로 텐서 만들기
print(floatvec.dtype)  # 텐서의 데이터 타입 확인

torch.float32


   - 정밀도와 계산 효율성 사이의 균형을 맞추기 위해 다양한 데이터 타입을 선택할 수 있다.
      - 32비트 부동 소수점 숫자는 대부분의 딥러닝 작업에 충분한 정밀도이다.
         - 64비트 부동 소숫점 숫자보다 메모리가 적게 들고 계산 비용이 저렴하다
         - GPU 구조가 32비트 계산에 최적화되어 있어 모델 훈련과 추론 속도가 빨라진다.
   - .to(dtype)를 사용해 텐서의 데이터 타입을 변경할 수 있다.

In [ ]:
floatvec = tensor1d.to(torch.float32)  # 텐서의 데이터 타입 변경
print(floatvec.dtype)  # 변경된 텐서의 데이터 타입 확인

torch.float32


6. 자주 사용하는 파이토치 연산 
   - reshape과 view 메서드 사이에는 미묘한 차이가 있다.
      - reshape
         - 새로운 텐서를 반환하며, 원본 텐서의 데이터를 변경하지 않는다. 메모리 복사가 발생할 수 있다.
         - 데이터 연속적으로 놓여 있지 않은 경우 reshape은 메모리 복사를 수행하여 새로운 텐서를 생성한다.
      - view
         - 원본 텐서의 뷰(view)를 반환하며, 데이터는 공유된다. 메모리 복사가 발생하지 않는다. 따라서 view는 reshape보다 더 효율적이다.
         - 데이터가 연속적으로 놓여 있지 않은 경우 view는 오류를 발생시킨다.


In [19]:
# 새로운 텐서 생성
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,"\n")

# 2개의 행과 3개의 열로 구성된 2차원 텐서
print("텐서의 형태 확인 :\n" , tensor2d.shape,"\n")

# 3 * 2 텐서로 변경
print("3 * 2 텐서로 변경 (reshape):\n" , tensor2d.reshape(3,2),"\n")
print("3 * 2 텐서로 변경 (view):\n" , tensor2d.view(3,2),"\n")  # 파이토치에서 reshape 보다 view를 더 많이 사용한다.

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

텐서의 형태 확인 :
 torch.Size([2, 3]) 

3 * 2 텐서로 변경 (reshape):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

3 * 2 텐서로 변경 (view):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 



   - .T를 사용해 텐서를 전치(transpose)할 수 있다.
      - 주 대각선을 기준으로 행과 열을 바꾼다.
      - 2차원 텐서(행렬)에만 적용할 수  있으며, transpose(0, 1)과 동일하다.

In [23]:
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,tensor2d.shape,"\n")
print("텐서 전치 (.T):\n" , tensor2d.T, tensor2d.T.shape,"\n")
print("텐서 전치 (.transpose):\n" , tensor2d.transpose(0, 1), tensor2d.transpose(0, 1).shape,"\n")

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) 

텐서 전치 (.T):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 

텐서 전치 (.transpose):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 



      - 두 행렬을 곱하는 방법은 matmul 연산자 또는 @ 기호를 사용하는 것이다.


In [25]:
print("tensor2d:\n", tensor2d, "\n")
print("tensor2d.T:\n", tensor2d.T, "\n")
print("tensor2d.matmul(tensor2d.T):\n", tensor2d.matmul(tensor2d.T), "\n")
print("tensor2d @ tensor2d.T:\n", tensor2d @ tensor2d.T, "\n")

tensor2d:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor2d.T:
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) 

tensor2d.matmul(tensor2d.T):
 tensor([[14, 32],
        [32, 77]]) 

tensor2d @ tensor2d.T:
 tensor([[14, 32],
        [32, 77]]) 

