# 파이토치 소개 목차
* [Chapter 1 파이토치란 무엇인가요?](#chapter1)
* [Chapter 2 텐서 이해하기](#chapter2)
* [Chapter 3 모델을 계산 그래프로 보기](#chapter3)
* [Chapter 4 자동 미분을 쉽게](#chapter4)
* [Chapter 5 다층 신경망 만들기](#chapter5)
* [Chapter 6 효율적인 데이터 로더 설정하기](#chapter6)
* [Chapter 7 일반적인 훈련 루프](#chapter7)
* [Chapter 8 모델 저장과 로드](#chapter8)

## Chapter 1 파이토치란 무엇인가요? <a class="anchor" id="chapter1"></a>
1. 파이토치 개요
   - 오픈 소스 파이썬 기반 딥러닝 라이브러리이다.
   - 파이토치는 크게 텐서 라이브러리, 자동 미분엔진, 딥러닝 라이브러리 세 가지 주요 구성 요소를 갖는다.
      - 텐서 라이브러리: 넘파이 개념을 확장하여 GPU로 계산을 가속하하는 기징이 추된 배열 지향 프로그래밍 라이브러리
      - 자동 미분엔진: 텐서 연산에 대하 자동으로 그레이디언트를 계산할 수 있어 간단하게 역전파와 모델 최적화를 수행한다.
      - 딥러닝 라이브러리: 다양한 딥러닝 모델을 구축하고 훈련하기 위해 모듈화되어 있다.

         ![구조](image/A-01-structure2.png)

2. 딥러닝 이란
   - AI(인공지능): 사람의 지능이 필요한 작업을 수행할 수 있는 컴퓨터 시스템을 만드는 것
   - 머신러닝
      - AI의 하위 분야로, 학습 알고리즘을 개발하고 향상시키는 데 초점을 맞춘다.
      - 작업을 명시적으로 프로그래밍하지 않고도 데이터에서 학습하여 예측을 만들거나 결정을 내리도록 한다.
   - 딥러닝
      - 머신러닝의 하위 분야로, 인공 신경망을 사용하여 데이터에서 학습한다.
      - 여러 층의 신경망을 사용하여 복잡한 패턴과 표현을 학습한다.
      - 이미지 인식, 자연어 처리, 음성 인식 등 다양한 분야에서 뛰어난 성능을 발휘한다.

3. 딥러닝 학습 단계
   - 학습 알고리즘을 사용해 샘플과 레이블로 구성된 훈련 데이터셋에서 모델을 훈련한다.
      - 예) 스팸 분류기인 경우 이베일과 사람이 분류한 '스펨', '스펨 아님'레이블로 훈련 데이터 셋을 구성한다.
   - 훈련된 모델을 사용해 새로운 샘플을 예측한다.
   - 훈련 단계와 추론 단계 사이에 모델 평가를 추가하여 모델을 실전 애플리케이션에 사용되기 전에 성능을 측정한다.

      ![단계](image/A-01-step2.png)

## Chapter 2 텐서 이해하기 <a class="anchor" id="chapter2"></a>
1. 텐서는 벡터와 행렬을 더 높은 차원으로 일반화한 수학적 개념이다
   - 텐서는 차원 개수를 나타내는 차수(rank or order)로 특징이 결정되는 수학적 객체이다.

      ![텐서](image/A-02-tensor.png)

2. 계산의 측면에서 보면 텐서는 데이터 컨테이너 역할을 한다.
   - 텐서는 다차원 데이터를 담고있다.
   - 각 차원은 서로 다은 특성을 나타낸다.
      - 예) 이미지 데이터의 경우, 높이, 너비, 색상 채널이 각각 텐서의 차원을 나타낸다.
   - 이런 맥락에서 텐서 라이브러리는 배열 라이브러리의 역활을 한다.

3. 파이토치 텐서는 넘파이 배열과 비슷하지만 딥러닝에서 중요한 몇 가지 추가 기능을 가지고 있다.
   - GPU 가속: 파이토치 텐서는 GPU에서 실행될 수 있어 대규모 행렬 연산을 가속화한다.
   - 자동 미분: 파이토치 텐서는 자동 미분 기능을 제공하여 신경망의 역전파를 쉽게 구현할 수 있다.
   - 동적 계산 그래프: 파이토치는 동적 계산 그래프를 사용하여 유연한 모델 정의와 디버깅을 가능하게 한다.

4. 스칼라, 벡터, 행렬, 텐서
   - 스칼라(0차원 텐서): 단일 숫자 값
   - 벡터(1차원 텐서): 숫자의 1차원 배열
   - 행렬(2차원 텐서): 숫자의 2차원 배열
   - 고차원 텐서(3차원 이상): 3차원 이상의 배열로, 예를 들어 이미지 데이터는 (높이, 너비, 채널) 형태의 3차원 텐서로 표현된다.



In [40]:
# 파이토치 텐서 만들기
import torch

tensor0d = torch.tensor(1) # 파이썬 0차원 정수 - 스칼라 (0차원 텐서)
tensor1d = torch.tensor([1, 2, 3]) # 파이썬 1차원 리스트 - 벡터 (1차원 텐서)
tensor2d = torch.tensor([[1, 2], [3, 4]]) # 중첩된 파이썬리스트로  2차원 텐서(행렬)
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 중첩된 파이썬리스트로 3차원 텐서

5. 텐서의 데이터 타입
   - 파이토치 정수의 데이터 타입은 기본적으로 64비트를 사용한다.
   - .dtype를 통해 텐서의 데이터 타입을 확인할 수 있다.

In [41]:
tensor1d.dtype  # 텐서의 데이터 타입 확인

torch.int64

   - 파이썬 부동 소수점 숫자로 텐서를 맏르면 파이토치는 기본적으로 32비트 부동 소수점 숫자를 사용한다.

In [42]:
floatvec = torch.tensor([1.0, 2.0, 3.0])  # 파이썬 부동 소수점 숫자로 텐서 만들기
print(floatvec.dtype)  # 텐서의 데이터 타입 확인

torch.float32


   - 정밀도와 계산 효율성 사이의 균형을 맞추기 위해 다양한 데이터 타입을 선택할 수 있다.
      - 32비트 부동 소수점 숫자는 대부분의 딥러닝 작업에 충분한 정밀도이다.
         - 64비트 부동 소숫점 숫자보다 메모리가 적게 들고 계산 비용이 저렴하다
         - GPU 구조가 32비트 계산에 최적화되어 있어 모델 훈련과 추론 속도가 빨라진다.
   - .to(dtype)를 사용해 텐서의 데이터 타입을 변경할 수 있다.

In [43]:
floatvec = tensor1d.to(torch.float32)  # 텐서의 데이터 타입 변경
print(floatvec.dtype)  # 변경된 텐서의 데이터 타입 확인

torch.float32


6. 자주 사용하는 파이토치 연산 
   - reshape과 view 메서드 사이에는 미묘한 차이가 있다.
      - reshape
         - 새로운 텐서를 반환하며, 원본 텐서의 데이터를 변경하지 않는다. 메모리 복사가 발생할 수 있다.
         - 데이터 연속적으로 놓여 있지 않은 경우 reshape은 메모리 복사를 수행하여 새로운 텐서를 생성한다.
      - view
         - 원본 텐서의 뷰(view)를 반환하며, 데이터는 공유된다. 메모리 복사가 발생하지 않는다. 따라서 view는 reshape보다 더 효율적이다.
         - 데이터가 연속적으로 놓여 있지 않은 경우 view는 오류를 발생시킨다.


In [44]:
# 새로운 텐서 생성
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,"\n")

# 2개의 행과 3개의 열로 구성된 2차원 텐서
print("텐서의 형태 확인 :\n" , tensor2d.shape,"\n")

# 3 * 2 텐서로 변경
print("3 * 2 텐서로 변경 (reshape):\n" , tensor2d.reshape(3,2),"\n")
print("3 * 2 텐서로 변경 (view):\n" , tensor2d.view(3,2),"\n")  # 파이토치에서 reshape 보다 view를 더 많이 사용한다.

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

텐서의 형태 확인 :
 torch.Size([2, 3]) 

3 * 2 텐서로 변경 (reshape):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

3 * 2 텐서로 변경 (view):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 



   - .T를 사용해 텐서를 전치(transpose)할 수 있다.
      - 주 대각선을 기준으로 행과 열을 바꾼다.
      - 2차원 텐서(행렬)에만 적용할 수  있으며, transpose(0, 1)과 동일하다.

In [45]:
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,tensor2d.shape,"\n")
print("텐서 전치 (.T):\n" , tensor2d.T, tensor2d.T.shape,"\n")
print("텐서 전치 (.transpose):\n" , tensor2d.transpose(0, 1), tensor2d.transpose(0, 1).shape,"\n")

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) 

텐서 전치 (.T):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 

텐서 전치 (.transpose):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 



      - 두 행렬을 곱하는 방법은 matmul 연산자 또는 @ 기호를 사용하는 것이다.


In [46]:
print("tensor2d:\n", tensor2d, "\n")
print("tensor2d.T:\n", tensor2d.T, "\n")
print("tensor2d.matmul(tensor2d.T):\n", tensor2d.matmul(tensor2d.T), "\n")
print("tensor2d @ tensor2d.T:\n", tensor2d @ tensor2d.T, "\n")

tensor2d:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor2d.T:
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) 

tensor2d.matmul(tensor2d.T):
 tensor([[14, 32],
        [32, 77]]) 

tensor2d @ tensor2d.T:
 tensor([[14, 32],
        [32, 77]]) 



## Chapter 3 모델을 계산 그래프로 보기 <a class="anchor" id="chapter3"></a>
1. 파이토치의 자동 미분 엔진(autograde)은 동적 계산 그래프(dynamic computation graph)에서 자동으로 그레이디언트를 계산한다.
   - 계산 그래프는 수학식을 표현하고 시각화할 수 있는 유향 그래프(DAG, directed acyclic graph)이다.
      - 유향 그래프: 그래프의 간선이 방향성을 가지며, 한 방향으로만 이동할 수 있다.
   - 딥러닝 측면에서 보면 계산 그래프는 신경망의 연산과 데이터 흐름을 나타낸다.
      - 노드(node): 텐서 연산(예: 덧셈, 곱셈, 행렬 곱셈 등)을 나타낸다.
      - 엣지(edge): 텐서 데이터를 나타내며, 노드 간의 데이터 흐름을 나타낸다.
   - 신경망의 핵심 알고리즘인 역전파를 위해 그레이디언트를 계산하려면 이 그래프가 필요하다

2. 간단한 로지스틱 회귀 분류기의 정방향 계산(forward computation) 예시
   - 하나의 층을 가진 신경망
   - 모델은 0과 1 사이의 점수를 반환
   - 정답 클레스 레이블(0 또는 1)과 비교하여 손실(loss)을 계산
   - 파이토치는 백그라운드에서 아래와 같은 계산 그래프를 만든다.
      - 그래프를 사용해 모델 파라미터에 대한 손실 함수의 그레이디언트를 계산하여 모델을 훈련할 수 있다

      ![계산 그래프](image/A-03-graph.png)

In [47]:
import torch.nn.functional as F
import torch

y = torch.tensor([1.0])  # 정답 레이블
x1 = torch.tensor([1.1])  # 입력 특성
w1 = torch.tensor([2.2])  # 가중치 파라미터
b = torch.tensor([0.0])   # 편향 유닛

# 단일 뉴런의 순전파 계산
z = x1 * w1 + b  # 가중치 곱셈 및 편향 더하기
print("선형 변환 결과 z:", z.item())  

a = torch.sigmoid(z)  # 시그모이드 활성화 함수 적용
print("활성화 출력 a:", a.item())  

loss = F.binary_cross_entropy(a, y)  # 이진 크로스 엔트로피 손실 계산
print("손실 값:", loss.item())

선형 변환 결과 z: 2.4200000762939453
활성화 출력 a: 0.918339729309082
손실 값: 0.0851878821849823


## Chapter 4 자동 미분을 쉽게 <a class="anchor" id="chapter4"></a>
1. 파이토치로 계산을 수행할 때 종단 노드(terminal node)중 하나의 requires_grade 속성이 True이면 파이토치는 자동으로 계산 그래프를 생성한다.
   - requires_grad 속성은 텐서가 그레이디언트를 계산해야 하는지 여부를 지정한다.
   - 기본적으로 requires_grad 속성은 False로 설정되어 있다

2. 역전파는 아래의 그림에서 볼 수 있듯이 신경망을 위한 미분의 연쇄 법칙(chain rule)을 구현한다.
   - 각 노드는 자신과 연결된 이전 노드에 대한 그레이디언트를 계산하는 방법을 알고 있다.
   - 역전파는 출력 노드에서 시작하여 그래프를 거슬러 올라가면서 각 노드의 그레이디언트를 계산한다.
   - 신경망에 있는 각 파라미터에 대한 손실 그레이디언트를 계산하는 데 사용된다.
   - 그레이디언트는 훈련 과정에서 이런 파라미터를 얼마나 업데이트해야 하는지 알려준다.

      ![역전파](image/A-04-auto2.png)

3. 편도 함수와 그레이디언트
   - 위의 그림에은 변수 중 하나에 대한 함수의 변화율을 측정하는 편도 함수(partial derivative)를 계산하는 방법을 보여준다.
   - 그레이디언트란 1개 이상의 변수를 입력으로 받는 다변수 함수(multivariable function)의 편도 함수들을 모아놓은 벡터이다.
      - 예를 들어, 함수 f(x, y)가 있을 때, x에 대한 편도 함수는 ∂f/∂x로 표기되고, y에 대한 편도 함수는 ∂f/∂y로 표기된다.
   - 고수준에서 연쇄 법칙이 계산 그래프에 있는 모델 파라미터에 대한 손실 그레이디언트를 계산하는 방법이다라고 이해할 수 있다.
   - 이를 통해 손실 함수를 최소화하기 위해 각 파라미터를 업데이트하는 데 필요한 정보를 얻는다.
   - 손실 함수는 경사 하강법과 같은 방법을 사용해 모델 성능을 측정하는 대리자 역할을 한다.

4. 파이토치의 자동 미분 엔진은 텐서에 대해 수행하는 모든 연산을 추적하여 백그라운드에서 계산 그래프를 구축한다.
   - .backward() 메서드를 호출하면 파이토치는 그래프를 거슬러 올라가면서 각 노드의 그레이디언트를 계산한다.
   - 계산된 그레이디언트는 텐서의 .grad 속성에 저장된다.
   - 예를 들어, 손실 텐서에 대해 .backward()를 호출하면 모델 파라미터에 대한 손실 그레이디언트가 계산되고 각 파라미터 텐서의 .grad 속성에 저장된다.
   

In [48]:
import torch
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])  # 정답 레이블
x1 = torch.tensor([1.1])  # 입력 특성
w1 = torch.tensor([2.2], requires_grad=True)  # 가중치 파라미터 (자동 미분 활성화)
b = torch.tensor([0.0], requires_grad=True)   # 편향 유닛 (자동 미분 활성화)

# 단일 뉴런의 순전파 계산
z = x1 * w1 + b  # 가중치 곱셈 및 편향 더하기
a = torch.sigmoid(z)  # 시그모이드 활성화 함수 적용

loss = F.binary_cross_entropy(a, y)  # 이진 크로스 엔트로피 손실 계산

# retain_graph=True 옵션을 사용하여 그래프를 유지
#   - 그레이디언트 계산 후에 메모리에서 해제가 기본
#   - 그래프를 금방 재사용하기위해 True 설정
grad_L_W1 = grad(loss, w1, retain_graph=True)  # 손실에 대한 가중치의 기울기 계산
grad_L_b = grad(loss, b, retain_graph=True)  # 손실에 대한 편향의 기울기 계산

print("grad_L_W1:", grad_L_W1)
print("grad_L_b:", grad_L_b)

grad_L_W1: (tensor([-0.0898]),)
grad_L_b: (tensor([-0.0817]),)


5. 파이토치는 손실 함수의 backward() 메서드를 호출하여 모델 파라미터에 대한 그레이디언트를 자동으로 계산한다.
   - 텐서의 .grad 속성에 그레이디언트가 저장된다.

In [49]:
loss.backward()  # 손실에 대한 모든 파라미터의 그레이디언트 계산
print("w1의 그레이디언트:", w1.grad)
print("b의 그레이디언트:", b.grad)

w1의 그레이디언트: tensor([-0.0898])
b의 그레이디언트: tensor([-0.0817])


## Chapter 5 다층 신경망 만들기 <a class="anchor" id="chapter5"></a>
1. 파이토치로 신경망을 만들 때 torch.nn.Module 클래스를 상속하여 사용자 정의 신경망 클래스를 정의한다.
   - 신경망의 계층과 파라미터를 관리하는 기본 클래스이다.
   - nn.Module을 상속한 클래스
      - __init__ 메서드에서 신경망의 계층을 정의
      - forward 메서드에서 순전파 계산을 구현한다.
         - forward 메서드에는 입력 데이터가 신경망을 어떻게 통과하여 계산 그래프로 구성되는지 기술한다.
      - backward 메서드를 사용해 모델 파라미터에 대한 손실 함수의 그레이디언트를 계산한다.
         - 하지만 일반적으로 backward 메서드를 직접 구현할 필요는 없다.
         - 파이토치의 자동 미분 엔진이 계산 그래프를 기반으로 자동으로 그레이디언트를 계산한다.
   - 층과 연산을 캡슐화하고 모델 파라미터를 추적할 수 있다

      ![다층 퍼셉트론](image/A-05-per.png)

2. 2개의 은닉층을 가진 다층 퍼셉트론(MLP, multi-layer perceptron) 예시
   
      


In [50]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs): # 특성 개수와 클래스 개수가 다른 데이터넷에 대응하기 위해 매개변수로 받음
        super().__init__()
        
        self.layers = torch.nn.Sequential(
            
            # 첫 번째 은닉층
            torch.nn.Linear(num_inputs, 30),  # Linear 층은 입력 개수와 출력 크기를 매개변수로 갖는다
            torch.nn.ReLU(),                   # 활성화 함수 ReLU
            
            # 두 번째 은닉층
            torch.nn.Linear(30, 20), # 은닉층의 입력 개수는 이전 층의 출력 크기와 동일
            torch.nn.ReLU(),
            
            # 출력층
            torch.nn.Linear(20, num_outputs)  # 출력층의 출력 크기는 클래스 개수와 동일
        )
    
    def forward(self, x):
        logits = self.layers(x)  # 순전파 계산
        return logits

In [51]:
model = NeuralNetwork(num_inputs=50, num_outputs=3)  # 입력 특성 50개, 클래스 3개인 모델 생성
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [52]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of trainable parameters: {num_params}")

Number of trainable parameters: 2213


   - 첫 번째 은닉층의 행력의 크기는 30 * 50 (입력 특성 50개, 은닉 유닛 30개), requires_grad=True
   - 첫 번째 은닉층의 가중치는 작은 난수로 초기화 되므로 신경망을 만들때마다 달라진다.
      - 딥러닝에서는 훈련 과정에서 대칭성을 깨뜨리기 위해 가중치를  작은 난수로 초기화하는 것이 좋다.

In [53]:
print(model.layers[0].weight) # 첫 번째 Linear 층의 가중치 파라미터

Parameter containing:
tensor([[-0.1146,  0.0116,  0.0874,  ..., -0.0681, -0.0891, -0.0696],
        [-0.0106, -0.0170, -0.1072,  ...,  0.1209, -0.0912, -0.0088],
        [-0.0460, -0.1340, -0.1263,  ..., -0.0938, -0.1335, -0.1205],
        ...,
        [ 0.0160,  0.1207,  0.1015,  ..., -0.0043,  0.0430,  0.1027],
        [ 0.0850, -0.1346,  0.0380,  ..., -0.0783, -0.0825,  0.0896],
        [-0.1107, -0.0485,  0.0618,  ...,  0.0039, -0.0099, -0.1152]],
       requires_grad=True)


In [54]:
print(model.layers[0].weight.shape)
print(model.layers[2].weight.shape)

torch.Size([30, 50])
torch.Size([20, 30])


In [55]:
print(model.layers[0].bias) # 첫 번째 Linear 층의 편향 파라미터

Parameter containing:
tensor([-0.1105,  0.0472,  0.0131,  0.0366, -0.1277,  0.0792, -0.0146,  0.0551,
        -0.0780,  0.0295,  0.0728, -0.1057,  0.0126, -0.0490,  0.1161, -0.0296,
        -0.0827, -0.0906, -0.0129,  0.0642,  0.0479,  0.1285,  0.1095,  0.0233,
         0.0390, -0.0612,  0.0496,  0.1086, -0.0029,  0.0272],
       requires_grad=True)


    - manual_seed() 함수를 사용해 난수 생성기를 시드(seed)로 설정하여 재현 가능한 결과를 얻을 수 있다.

In [56]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=50, num_outputs=3)  # 입력 특성 50개, 클래스 3개인 모델 생성
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


- 정방향 계산에서 신경망 사용
   - 50개의 특성을 가진 입력을 주입하고 3개의 클래스에 대한 출력 로짓을 얻는다
   - 정방향 계산은 입력 텐서로부터 출력 텐서를 계산하는 것을 의미한다.
   - 반환된 3개의 숫자는 3개의 출력노드에 할당된 점수이다.
   - 출력 텐서에 표시된 grad_fn=<AddmmBackward0>은 계산 그래프에서 변수를 계산하는데 마지막에 사용된 함수를 나타낸다.
      -  <AddmmBackward0>는 텐서가 행렬 곱셈과 덧셈 연산을 통해 만들어 졌다는 것을 의미한다.
         - Addmm는 행렬 곱셈(mm:matrix multiplication)과 덧셈(Add:addition)을 결합한 연산을 나타낸다.
      - 파이토치는 역전파 과정에서 그레이디언트를 계산할 때 이 정보를 사용한다.

In [57]:
torch.manual_seed(123)
X = torch.rand(1, 50)  # 배치 크기 1, 특성 개수 50인 무작위 입력 텐서 생성
out = model(X)  # 신경망에 입력 텐서 전달하여 정방향 계산 수행
print(out)  # 출력 로짓 텐서 출력

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


-  훈련이나 역전파 없이 신경망을 사용하기만 한다면(훈련이 끝난 후 예측 시) 이런 구성을 하는 것은 추가 자원을 소모하기 때문에 권장되지 않는다.
   - torch.no_grad() 컨텍스트 매니저를 사용해 불필요한 계산 그래프 생성을 방지할 수 있다.

In [58]:
with torch.no_grad():
    out = model(X)

print(out)  # 출력 로짓 텐서 출력

tensor([[-0.1262,  0.1080, -0.1792]])


   - 파이토치에서는 모델의 마지막 층의 출력(로짓)을 비선형 활성화 함수에 통과시키지 않고 출력하는 것이 일반적이다.
      - 이는 파이토치에서 널리 사용되는 손실 함수가 softmax(이진 분류일 경우 sigmoid) 연산과 음의 로그 가능도 손실을 하나의 클래스로 결합하고 있기 때문이다.
        - 예를 들어, nn.CrossEntropyLoss 손실 함수는 내부적으로 소프트맥스 연산을 수행하므로 모델의 출력에 소프트맥스를 적용할 필요가 없다.
      - 모델의 예측에 대한 클래스 소속 확률을 얻고 싶다면 명시적으로 softmax 연산을 적용해야 한다.

In [59]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)

# 훈련하지 않고 랜덤하게 초기화된 모델이므로 클래스의 확률이 거의 비슷하다.
print(out)  # 출력 확률 텐서 출력

tensor([[0.3113, 0.3934, 0.2952]])


## Chapter 6 효율적인 데이터 로더 설정하기 <a class="anchor" id="chapter6"></a>
1. 파이토치는 Dataset과 DataLoader라는 두 가지 주요 클래스를 제공하여 데이터셋을 효율적으로 관리하고 배치 단위로 데이터를 로드할 수 있도록 한다.
   - Dataset 클래스는 데이터셋의 샘플과 레이블에 접근하는 방법을 정의한다.
   - DataLoader 클래스는 Dataset에서 데이터를 배치 단위로 로드하고, 셔플링(shuffling) 및 병렬 처리(parallel processing)를 지원한다.

      ![데이터 로더](image/A-06-dataLoader.png)

2. Dataset 클래스 구현하여 훈련 데이터셋과 테스트 데이터셋 생성
   - 5개의 샘플과 2개의 특성을 가진 훈련 데이터셋을 만든다.
      - 3개의 샘플은 클래스 0, 2개의 샘플은 클래스 1에 속한다.
   - 2개의 샘플과 2개의 특성을 가진 테스트 데이터셋을 만든다.
      - 1개의 샘플은 클래스 0, 1개의 샘플은 클래스 1에 속한다.

In [60]:
import torch

X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])  # 이진 분류 레이블

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6]
])

y_test = torch.tensor([0, 1])  # 이진 분류 레이블

3. Dataset 클래스를 상속하여 사용자 정의 데이터 클래스 ToyDataset을 만든다.
   - __init__ 메서드에서 데이터셋의 샘플과 레이블을 초기화한다.
   - __len__ 메서드에서 데이터셋의 샘플 수를 반환한다.
   - __getitem__ 메서드에서 주어진 인덱스에 해당하는 샘플과 레이블을 반환한다.
   - ToyDataset의 목적은 파이토치 DataLoader의 객체를 만드는 것이다.

In [61]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.feautures = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.feautures[index]
        one_y = self.labels[index]
        return one_x, one_y
    
    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [62]:
print("훈련 데이터셋 샘플 수:", len(train_ds))
print("테스트 데이터셋 샘플 수:", len(test_ds))

훈련 데이터셋 샘플 수: 5
테스트 데이터셋 샘플 수: 2


4. DataLoader 클래스를 사용한 데이터 샘플링
   - DataLoader 객체를 생성할 때 Dataset 객체를 전달하고, 배치 크기(batch_size)와 셔플링 여부(shuffle)를 지정한다.
   - DataLoader는 지정된 배치 크기만큼 데이터를 로드하고, 셔플링이 True로 설정된 경우 데이터셋을 무작위로 섞는다.
   - DataLoader 객체를 반복(iterate)하여 배치 단위로 데이터를 가져올 수 있다.
   - 각 배치는 입력 텐서와 레이블 텐서로 구성된다.
   - 정확히 한 번씩 샘플을 방문하고 전체 방문을 에폭(epoch)이라고 한다.
   - drop_last 매개변수를 True로 설정하면 마지막 배치가 지정된 배치 크기보다 작을 경우 해당 배치를 버린다.

In [63]:
from torch.utils.data import Dataset, DataLoader

torch.manual_seed(123)

train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=0)

test_loader = DataLoader(test_ds, batch_size=2, shuffle=False, num_workers=0)

for idx, (x, y) in enumerate(train_loader):
    print(f"배치 {idx+1}:")
    print("입력 텐서 x:\n", x)
    print("레이블 텐서 y:\n", y)
    print()


배치 1:
입력 텐서 x:
 tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]])
레이블 텐서 y:
 tensor([1, 0])

배치 2:
입력 텐서 x:
 tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]])
레이블 텐서 y:
 tensor([0, 0])

배치 3:
입력 텐서 x:
 tensor([[ 2.7000, -1.5000]])
레이블 텐서 y:
 tensor([1])



In [64]:
train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=0, drop_last=True)
for idx, (x, y) in enumerate(train_loader):
    print(f"배치 {idx+1}:")
    print("입력 텐서 x:\n", x)
    print("레이블 텐서 y:\n", y)
    print()

배치 1:
입력 텐서 x:
 tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]])
레이블 텐서 y:
 tensor([0, 0])

배치 2:
입력 텐서 x:
 tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]])
레이블 텐서 y:
 tensor([1, 0])



4. DataLoader의 num_workers 매개변수
   - num_workers 매개변수는 데이터 로딩에 사용할 하위 프로세스의 수를 지정한다.
   - 기본값은 0이며, 이 경우 메인 프로세스에서 데이터를 로드한다.
      - CPU가 딥러닝 모델을 처리하는 데만 집중하지 못하고 데이터 로드와 전처리에 도 관여하게 된다.
      - CPU가 이런 작업을 완료하는 동안 GPU가 유휴 상태가 될 수 있다.
   - num_workers를 1 이상의 값으로 설정하면 데이터 로딩이 병렬로 수행되어 데이터 로딩 속도가 향상될 수 있다.
      - 그러나 너무 많은 워커를 사용하면 오히려 성능이 저하될 수 있으므로 적절한 값을 선택하는 것이 중요하다.

## Chapter 7 일반적인 훈련 루프 <a class="anchor" id="chapter7"></a>
1. 데이터셋으로 신경망 훈련
   - 세 번째 에포크 후에 손실이 0에 도달.
      - 모델이 훈련 세트에 대해 수렴했다는 것을 의미.
   - 실전에서는 최적의 하이퍼파라미터 설정을 찾기 위해 검증 데이터넷이라는 세번째 데이터셋을 사용한다.
      - 모델 평가가 편향되지 않도록 테스트 세트는 딱 한번만 사용해야한다.
      - 검증 세트는 모델 설정을 조정하기 위해 여러번 사용할 수 있다.

In [65]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)  # 입력 특성 2개, 클래스 2개인 모델 생성
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)  # 확률적 경사 하강법 옵티마이저 설정

num_epochs = 3 # 훈련 에폭 수
for epoch in range(num_epochs):
    model.train()  # 모델을 훈련 모드로 설정
    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)  # 모델에 입력 특성 전달하여 로짓 계산
        loss = F.cross_entropy(logits, labels)  # 교차 엔트로피 손실 계산
        optimizer.zero_grad()  # 이전 그레이디언트 초기화
        loss.backward()  # 손실에 대한 그레이디언트 계산
        optimizer.step()  # 모델 파라미터 업데이트
        
        ## 로깅
        print(f"에폭 {epoch+1}/{num_epochs}, 배치 {batch_idx+1}/{len(train_loader)}, 손실: {loss.item():.2f}")
model.eval()  # 모델을 평가 모드로 설정

에폭 1/3, 배치 1/2, 손실: 0.75
에폭 1/3, 배치 2/2, 손실: 0.65
에폭 2/3, 배치 1/2, 손실: 0.44
에폭 2/3, 배치 2/2, 손실: 0.13
에폭 3/3, 배치 1/2, 손실: 0.03
에폭 3/3, 배치 2/2, 손실: 0.00


NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=2, bias=True)
  )
)

2. 모델을 훈련 시킨 다음 이를 샤용해 예측 실행

In [66]:
model.eval()  # 모델을 평가 모드로 설정
with torch.no_grad():  # 그레이디언트 계산 비활성화
    outputs = model(X_train)
    
print("훈련 데이터에 대한 모델 출력:\n", outputs)

훈련 데이터에 대한 모델 출력:
 tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


3. 클래스 확률 계산을 위해 소프트맥스 함수 적용

In [67]:
# sci_mode=False 설정
#   - 지수 표기법 대신 일반 소수점 표기법으로 출력
torch.set_printoptions(sci_mode=False)  

# 소프트맥스 함수 적용
#   - dim=0: 각 열에 대해 소프트맥스 적용 (각 특성별로)
#   - dim=1: 각 행에 대해 소프트맥스 적용 (각 샘플별로)
probas = torch.softmax(outputs, dim=1)  
print("훈련 데이터에 대한 클래스 확률:\n", probas)

훈련 데이터에 대한 클래스 확률:
 tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])


In [68]:
predictions = torch.argmax(probas, dim=1)
print("훈련 데이터에 대한 예측 클래스:\n", predictions)

훈련 데이터에 대한 예측 클래스:
 tensor([0, 0, 0, 1, 1])


In [69]:
predictions = torch.argmax(outputs, dim=1)
print("훈련 데이터에 대한 예측 클래스:\n", predictions)

훈련 데이터에 대한 예측 클래스:
 tensor([0, 0, 0, 1, 1])


In [70]:
predictions == y_train
print(predictions == y_train)

print(torch.sum(predictions == y_train))

tensor([True, True, True, True, True])
tensor(5)


4. 예측 정확도 함수
   - 데이터 로더를 순회하면서 올바른 예측의 개수와 비율을 계산한다.

In [71]:
def compute_accuracy(model, dataloader):
    
    model.eval()  # 모델을 평가 모드로 설정
    correct = 0.0
    total_examples = 0
    
    for idx, (features, labels) in enumerate(dataloader):
        
        with torch.no_grad():
            logits = model(features)
            
        predictions = torch.argmax(logits, dim=1) # 예측 클래스 계산
        compare = labels == predictions  # 정답과 예측 비교
        correct += torch.sum(compare) # 정답 개수 누적
        total_examples += len(compare) # 전체 샘플 개수 누적
        
    return correct.item() / total_examples

In [72]:
print(compute_accuracy(model, train_loader))

print(compute_accuracy(model, test_loader))

1.0
1.0


## Chapter 8 모델 저장과 로드 <a class="anchor" id="chapter8"></a>
1 . 모델 저장
   - torch.save() 함수를 사용해 모델의 상태 사전을 파일에 저장한다.
   - 상태 사전(state_dict)은 모델의 파라미터와 버퍼를 포함하는 딕셔너리이다.
   - 일반적으로 모델의 가중치와 바이어스를 저장하는 데 사용된다.
   - 모델을 저장할 때는 파일 경로와 모델의 상태 사전을 전달한다.

In [73]:
torch.save(model.state_dict(), "toy_model.pth")  # 모델의 상태 사전을 파일에 저장

In [75]:

model = NeuralNetwork(num_inputs=2, num_outputs=2)  # 동일한 모델 구조로 새 모델 생성
model.load_state_dict(torch.load("toy_model.pth"))  # 저장된 상태 사전을 로드하여 모델 파라미터 복원
model.eval()  # 모델을 평가 모드로 설정

print(compute_accuracy(model, train_loader))



1.0
