# 파이토치 소개 목차
* [Chapter 1 파이토치란 무엇인가요?](#chapter1)
* [Chapter 2 텐서 이해하기](#chapter2)
* [Chapter 3 모델을 계산 그래프로 보기](#chapter3)
* [Chapter 4 자동 미분을 쉽게](#chapter4)
* [Chapter 5 다층 신경망 만들기](#chapter5)


## Chapter 1 파이토치란 무엇인가요? <a class="anchor" id="chapter1"></a>
1. 파이토치 개요
   - 오픈 소스 파이썬 기반 딥러닝 라이브러리이다.
   - 파이토치는 크게 텐서 라이브러리, 자동 미분엔진, 딥러닝 라이브러리 세 가지 주요 구성 요소를 갖는다.
      - 텐서 라이브러리: 넘파이 개념을 확장하여 GPU로 계산을 가속하하는 기징이 추된 배열 지향 프로그래밍 라이브러리
      - 자동 미분엔진: 텐서 연산에 대하 자동으로 그레이디언트를 계산할 수 있어 간단하게 역전파와 모델 최적화를 수행한다.
      - 딥러닝 라이브러리: 다양한 딥러닝 모델을 구축하고 훈련하기 위해 모듈화되어 있다.

         ![구조](image/A-01-structure2.png)

2. 딥러닝 이란
   - AI(인공지능): 사람의 지능이 필요한 작업을 수행할 수 있는 컴퓨터 시스템을 만드는 것
   - 머신러닝
      - AI의 하위 분야로, 학습 알고리즘을 개발하고 향상시키는 데 초점을 맞춘다.
      - 작업을 명시적으로 프로그래밍하지 않고도 데이터에서 학습하여 예측을 만들거나 결정을 내리도록 한다.
   - 딥러닝
      - 머신러닝의 하위 분야로, 인공 신경망을 사용하여 데이터에서 학습한다.
      - 여러 층의 신경망을 사용하여 복잡한 패턴과 표현을 학습한다.
      - 이미지 인식, 자연어 처리, 음성 인식 등 다양한 분야에서 뛰어난 성능을 발휘한다.

3. 딥러닝 학습 단계
   - 학습 알고리즘을 사용해 샘플과 레이블로 구성된 훈련 데이터셋에서 모델을 훈련한다.
      - 예) 스팸 분류기인 경우 이베일과 사람이 분류한 '스펨', '스펨 아님'레이블로 훈련 데이터 셋을 구성한다.
   - 훈련된 모델을 사용해 새로운 샘플을 예측한다.
   - 훈련 단계와 추론 단계 사이에 모델 평가를 추가하여 모델을 실전 애플리케이션에 사용되기 전에 성능을 측정한다.

      ![단계](image/A-01-step2.png)

## Chapter 2 텐서 이해하기 <a class="anchor" id="chapter2"></a>
1. 텐서는 벡터와 행렬을 더 높은 차원으로 일반화한 수학적 개념이다
   - 텐서는 차원 개수를 나타내는 차수(rank or order)로 특징이 결정되는 수학적 객체이다.

      ![텐서](image/A-02-tensor.png)

2. 계산의 측면에서 보면 텐서는 데이터 컨테이너 역할을 한다.
   - 텐서는 다차원 데이터를 담고있다.
   - 각 차원은 서로 다은 특성을 나타낸다.
      - 예) 이미지 데이터의 경우, 높이, 너비, 색상 채널이 각각 텐서의 차원을 나타낸다.
   - 이런 맥락에서 텐서 라이브러리는 배열 라이브러리의 역활을 한다.

3. 파이토치 텐서는 넘파이 배열과 비슷하지만 딥러닝에서 중요한 몇 가지 추가 기능을 가지고 있다.
   - GPU 가속: 파이토치 텐서는 GPU에서 실행될 수 있어 대규모 행렬 연산을 가속화한다.
   - 자동 미분: 파이토치 텐서는 자동 미분 기능을 제공하여 신경망의 역전파를 쉽게 구현할 수 있다.
   - 동적 계산 그래프: 파이토치는 동적 계산 그래프를 사용하여 유연한 모델 정의와 디버깅을 가능하게 한다.

4. 스칼라, 벡터, 행렬, 텐서
   - 스칼라(0차원 텐서): 단일 숫자 값
   - 벡터(1차원 텐서): 숫자의 1차원 배열
   - 행렬(2차원 텐서): 숫자의 2차원 배열
   - 고차원 텐서(3차원 이상): 3차원 이상의 배열로, 예를 들어 이미지 데이터는 (높이, 너비, 채널) 형태의 3차원 텐서로 표현된다.



In [1]:
# 파이토치 텐서 만들기
import torch

tensor0d = torch.tensor(1) # 파이썬 0차원 정수 - 스칼라 (0차원 텐서)
tensor1d = torch.tensor([1, 2, 3]) # 파이썬 1차원 리스트 - 벡터 (1차원 텐서)
tensor2d = torch.tensor([[1, 2], [3, 4]]) # 중첩된 파이썬리스트로  2차원 텐서(행렬)
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 중첩된 파이썬리스트로 3차원 텐서

5. 텐서의 데이터 타입
   - 파이토치 정수의 데이터 타입은 기본적으로 64비트를 사용한다.
   - .dtype를 통해 텐서의 데이터 타입을 확인할 수 있다.

In [2]:
tensor1d.dtype  # 텐서의 데이터 타입 확인

torch.int64

   - 파이썬 부동 소수점 숫자로 텐서를 맏르면 파이토치는 기본적으로 32비트 부동 소수점 숫자를 사용한다.

In [3]:
floatvec = torch.tensor([1.0, 2.0, 3.0])  # 파이썬 부동 소수점 숫자로 텐서 만들기
print(floatvec.dtype)  # 텐서의 데이터 타입 확인

torch.float32


   - 정밀도와 계산 효율성 사이의 균형을 맞추기 위해 다양한 데이터 타입을 선택할 수 있다.
      - 32비트 부동 소수점 숫자는 대부분의 딥러닝 작업에 충분한 정밀도이다.
         - 64비트 부동 소숫점 숫자보다 메모리가 적게 들고 계산 비용이 저렴하다
         - GPU 구조가 32비트 계산에 최적화되어 있어 모델 훈련과 추론 속도가 빨라진다.
   - .to(dtype)를 사용해 텐서의 데이터 타입을 변경할 수 있다.

In [ ]:
floatvec = tensor1d.to(torch.float32)  # 텐서의 데이터 타입 변경
print(floatvec.dtype)  # 변경된 텐서의 데이터 타입 확인

torch.float32


6. 자주 사용하는 파이토치 연산 
   - reshape과 view 메서드 사이에는 미묘한 차이가 있다.
      - reshape
         - 새로운 텐서를 반환하며, 원본 텐서의 데이터를 변경하지 않는다. 메모리 복사가 발생할 수 있다.
         - 데이터 연속적으로 놓여 있지 않은 경우 reshape은 메모리 복사를 수행하여 새로운 텐서를 생성한다.
      - view
         - 원본 텐서의 뷰(view)를 반환하며, 데이터는 공유된다. 메모리 복사가 발생하지 않는다. 따라서 view는 reshape보다 더 효율적이다.
         - 데이터가 연속적으로 놓여 있지 않은 경우 view는 오류를 발생시킨다.


In [19]:
# 새로운 텐서 생성
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,"\n")

# 2개의 행과 3개의 열로 구성된 2차원 텐서
print("텐서의 형태 확인 :\n" , tensor2d.shape,"\n")

# 3 * 2 텐서로 변경
print("3 * 2 텐서로 변경 (reshape):\n" , tensor2d.reshape(3,2),"\n")
print("3 * 2 텐서로 변경 (view):\n" , tensor2d.view(3,2),"\n")  # 파이토치에서 reshape 보다 view를 더 많이 사용한다.

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

텐서의 형태 확인 :
 torch.Size([2, 3]) 

3 * 2 텐서로 변경 (reshape):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

3 * 2 텐서로 변경 (view):
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 



   - .T를 사용해 텐서를 전치(transpose)할 수 있다.
      - 주 대각선을 기준으로 행과 열을 바꾼다.
      - 2차원 텐서(행렬)에만 적용할 수  있으며, transpose(0, 1)과 동일하다.

In [23]:
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print("새로운 텐서 생성 :\n" , tensor2d,tensor2d.shape,"\n")
print("텐서 전치 (.T):\n" , tensor2d.T, tensor2d.T.shape,"\n")
print("텐서 전치 (.transpose):\n" , tensor2d.transpose(0, 1), tensor2d.transpose(0, 1).shape,"\n")

새로운 텐서 생성 :
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) 

텐서 전치 (.T):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 

텐서 전치 (.transpose):
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) 



      - 두 행렬을 곱하는 방법은 matmul 연산자 또는 @ 기호를 사용하는 것이다.


In [25]:
print("tensor2d:\n", tensor2d, "\n")
print("tensor2d.T:\n", tensor2d.T, "\n")
print("tensor2d.matmul(tensor2d.T):\n", tensor2d.matmul(tensor2d.T), "\n")
print("tensor2d @ tensor2d.T:\n", tensor2d @ tensor2d.T, "\n")

tensor2d:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor2d.T:
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) 

tensor2d.matmul(tensor2d.T):
 tensor([[14, 32],
        [32, 77]]) 

tensor2d @ tensor2d.T:
 tensor([[14, 32],
        [32, 77]]) 



## Chapter 3 모델을 계산 그래프로 보기 <a class="anchor" id="chapter3"></a>
1. 파이토치의 자동 미분 엔진(autograde)은 동적 계산 그래프(dynamic computation graph)에서 자동으로 그레이디언트를 계산한다.
   - 계산 그래프는 수학식을 표현하고 시각화할 수 있는 유향 그래프(DAG, directed acyclic graph)이다.
      - 유향 그래프: 그래프의 간선이 방향성을 가지며, 한 방향으로만 이동할 수 있다.
   - 딥러닝 측면에서 보면 계산 그래프는 신경망의 연산과 데이터 흐름을 나타낸다.
      - 노드(node): 텐서 연산(예: 덧셈, 곱셈, 행렬 곱셈 등)을 나타낸다.
      - 엣지(edge): 텐서 데이터를 나타내며, 노드 간의 데이터 흐름을 나타낸다.
   - 신경망의 핵심 알고리즘인 역전파를 위해 그레이디언트를 계산하려면 이 그래프가 필요하다

2. 간단한 로지스틱 회귀 분류기의 정방향 계산(forward computation) 예시
   - 하나의 층을 가진 신경망
   - 모델은 0과 1 사이의 점수를 반환
   - 정답 클레스 레이블(0 또는 1)과 비교하여 손실(loss)을 계산
   - 파이토치는 백그라운드에서 아래와 같은 계산 그래프를 만든다.
      - 그래프를 사용해 모델 파라미터에 대한 손실 함수의 그레이디언트를 계산하여 모델을 훈련할 수 있다

      ![계산 그래프](image/A-03-graph.png)

In [2]:
import torch.nn.functional as F
import torch

y = torch.tensor([1.0])  # 정답 레이블
x1 = torch.tensor([1.1])  # 입력 특성
w1 = torch.tensor([2.2])  # 가중치 파라미터
b = torch.tensor([0.0])   # 편향 유닛

# 단일 뉴런의 순전파 계산
z = x1 * w1 + b  # 가중치 곱셈 및 편향 더하기
print("선형 변환 결과 z:", z.item())  

a = torch.sigmoid(z)  # 시그모이드 활성화 함수 적용
print("활성화 출력 a:", a.item())  

loss = F.binary_cross_entropy(a, y)  # 이진 크로스 엔트로피 손실 계산
print("손실 값:", loss.item())

선형 변환 결과 z: 2.4200000762939453
활성화 출력 a: 0.918339729309082
손실 값: 0.0851878821849823


## Chapter 4 자동 미분을 쉽게 <a class="anchor" id="chapter4"></a>
1. 파이토치로 계산을 수행할 때 종단 노드(terminal node)중 하나의 requires_grade 속성이 True이면 파이토치는 자동으로 계산 그래프를 생성한다.
   - requires_grad 속성은 텐서가 그레이디언트를 계산해야 하는지 여부를 지정한다.
   - 기본적으로 requires_grad 속성은 False로 설정되어 있다

2. 역전파는 아래의 그림에서 볼 수 있듯이 신경망을 위한 미분의 연쇄 법칙(chain rule)을 구현한다.
   - 각 노드는 자신과 연결된 이전 노드에 대한 그레이디언트를 계산하는 방법을 알고 있다.
   - 역전파는 출력 노드에서 시작하여 그래프를 거슬러 올라가면서 각 노드의 그레이디언트를 계산한다.
   - 신경망에 있는 각 파라미터에 대한 손실 그레이디언트를 계산하는 데 사용된다.
   - 그레이디언트는 훈련 과정에서 이런 파라미터를 얼마나 업데이트해야 하는지 알려준다.

      ![역전파](image/A-04-auto2.png)

3. 편도 함수와 그레이디언트
   - 위의 그림에은 변수 중 하나에 대한 함수의 변화율을 측정하는 편도 함수(partial derivative)를 계산하는 방법을 보여준다.
   - 그레이디언트란 1개 이상의 변수를 입력으로 받는 다변수 함수(multivariable function)의 편도 함수들을 모아놓은 벡터이다.
      - 예를 들어, 함수 f(x, y)가 있을 때, x에 대한 편도 함수는 ∂f/∂x로 표기되고, y에 대한 편도 함수는 ∂f/∂y로 표기된다.
   - 고수준에서 연쇄 법칙이 계산 그래프에 있는 모델 파라미터에 대한 손실 그레이디언트를 계산하는 방법이다라고 이해할 수 있다.
   - 이를 통해 손실 함수를 최소화하기 위해 각 파라미터를 업데이트하는 데 필요한 정보를 얻는다.
   - 손실 함수는 경사 하강법과 같은 방법을 사용해 모델 성능을 측정하는 대리자 역할을 한다.

4. 파이토치의 자동 미분 엔진은 텐서에 대해 수행하는 모든 연산을 추적하여 백그라운드에서 계산 그래프를 구축한다.
   - .backward() 메서드를 호출하면 파이토치는 그래프를 거슬러 올라가면서 각 노드의 그레이디언트를 계산한다.
   - 계산된 그레이디언트는 텐서의 .grad 속성에 저장된다.
   - 예를 들어, 손실 텐서에 대해 .backward()를 호출하면 모델 파라미터에 대한 손실 그레이디언트가 계산되고 각 파라미터 텐서의 .grad 속성에 저장된다.
   

In [3]:
import torch
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])  # 정답 레이블
x1 = torch.tensor([1.1])  # 입력 특성
w1 = torch.tensor([2.2], requires_grad=True)  # 가중치 파라미터 (자동 미분 활성화)
b = torch.tensor([0.0], requires_grad=True)   # 편향 유닛 (자동 미분 활성화)

# 단일 뉴런의 순전파 계산
z = x1 * w1 + b  # 가중치 곱셈 및 편향 더하기
a = torch.sigmoid(z)  # 시그모이드 활성화 함수 적용

loss = F.binary_cross_entropy(a, y)  # 이진 크로스 엔트로피 손실 계산

# retain_graph=True 옵션을 사용하여 그래프를 유지
#   - 그레이디언트 계산 후에 메모리에서 해제가 기본
#   - 그래프를 금방 재사용하기위해 True 설정
grad_L_W1 = grad(loss, w1, retain_graph=True)  # 손실에 대한 가중치의 기울기 계산
grad_L_b = grad(loss, b, retain_graph=True)  # 손실에 대한 편향의 기울기 계산

print("grad_L_W1:", grad_L_W1)
print("grad_L_b:", grad_L_b)

grad_L_W1: (tensor([-0.0898]),)
grad_L_b: (tensor([-0.0817]),)


5. 파이토치는 손실 함수의 backward() 메서드를 호출하여 모델 파라미터에 대한 그레이디언트를 자동으로 계산한다.
   - 텐서의 .grad 속성에 그레이디언트가 저장된다.

In [4]:
loss.backward()  # 손실에 대한 모든 파라미터의 그레이디언트 계산
print("w1의 그레이디언트:", w1.grad)
print("b의 그레이디언트:", b.grad)

w1의 그레이디언트: tensor([-0.0898])
b의 그레이디언트: tensor([-0.0817])


## Chapter 5 다층 신경망 만들기 <a class="anchor" id="chapter5"></a>
1. 파이토치로 신경망을 만들 때 torch.nn.Module 클래스를 상속하여 사용자 정의 신경망 클래스를 정의한다.
   - 신경망의 계층과 파라미터를 관리하는 기본 클래스이다.
   - nn.Module을 상속한 클래스
      - __init__ 메서드에서 신경망의 계층을 정의
      - forward 메서드에서 순전파 계산을 구현한다.
         - forward 메서드에는 입력 데이터가 신경망을 어떻게 통과하여 계산 그래프로 구성되는지 기술한다.
      - backward 메서드를 사용해 모델 파라미터에 대한 손실 함수의 그레이디언트를 계산한다.
         - 하지만 일반적으로 backward 메서드를 직접 구현할 필요는 없다.
         - 파이토치의 자동 미분 엔진이 계산 그래프를 기반으로 자동으로 그레이디언트를 계산한다.
   - 층과 연산을 캡슐화하고 모델 파라미터를 추적할 수 있다

      ![다층 퍼셉트론](image/A-05-per.png)

2. 2개의 은닉층을 가진 다층 퍼셉트론(MLP, multi-layer perceptron) 예시
   
      


In [6]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs): # 특성 개수와 클래스 개수가 다른 데이터넷에 대응하기 위해 매개변수로 받음
        super().__init__()
        
        self.layers = torch.nn.Sequential(
            
            # 첫 번째 은닉층
            torch.nn.Linear(num_inputs, 30),  # Linear 층은 입력 개수와 출력 크기를 매개변수로 갖는다
            torch.nn.ReLU(),                   # 활성화 함수 ReLU
            
            # 두 번째 은닉층
            torch.nn.Linear(30, 20), # 은닉층의 입력 개수는 이전 층의 출력 크기와 동일
            torch.nn.ReLU(),
            
            # 출력층
            torch.nn.Linear(20, num_outputs)  # 출력층의 출력 크기는 클래스 개수와 동일
        )
    
    def forward(self, x):
        logits = self.layers(x)  # 순전파 계산
        return logits

In [8]:
model = NeuralNetwork(num_inputs=50, num_outputs=3)  # 입력 특성 50개, 클래스 3개인 모델 생성
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [9]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of trainable parameters: {num_params}")

Number of trainable parameters: 2213


   - 첫 번째 은닉층의 행력의 크기는 30 * 50 (입력 특성 50개, 은닉 유닛 30개), requires_grad=True
   - 첫 번째 은닉층의 가중치는 작은 난수로 초기화 되므로 신경망을 만들때마다 달라진다.
      - 딥러닝에서는 훈련 과정에서 대칭성을 깨뜨리기 위해 가중치를  작은 난수로 초기화하는 것이 좋다.

In [10]:
print(model.layers[0].weight) # 첫 번째 Linear 층의 가중치 파라미터

Parameter containing:
tensor([[-0.0392,  0.0466,  0.0625,  ..., -0.0362,  0.0142,  0.0858],
        [ 0.1268,  0.0430,  0.0592,  ...,  0.0370, -0.0534, -0.0463],
        [ 0.1176, -0.0494, -0.1392,  ...,  0.1395, -0.1310, -0.0971],
        ...,
        [ 0.0793,  0.0363,  0.0996,  ..., -0.0921, -0.0359,  0.0387],
        [ 0.0742,  0.0951, -0.0473,  ..., -0.0192, -0.1336,  0.0664],
        [-0.1252,  0.0335,  0.0488,  ...,  0.0405, -0.1296,  0.0760]],
       requires_grad=True)


In [14]:
print(model.layers[0].weight.shape)
print(model.layers[2].weight.shape)

torch.Size([30, 50])
torch.Size([20, 30])


In [12]:
print(model.layers[0].bias) # 첫 번째 Linear 층의 편향 파라미터

Parameter containing:
tensor([-0.0334,  0.0284,  0.0842,  0.0976,  0.0243, -0.0441,  0.0523, -0.0286,
        -0.0757,  0.0653,  0.0347, -0.0432,  0.1254, -0.0821,  0.1068,  0.0703,
        -0.0411, -0.1216, -0.0663, -0.0605,  0.1109, -0.0683, -0.1176, -0.0951,
        -0.0636,  0.0354,  0.1181,  0.1286, -0.0157,  0.1207],
       requires_grad=True)


    - manual_seed() 함수를 사용해 난수 생성기를 시드(seed)로 설정하여 재현 가능한 결과를 얻을 수 있다.

In [17]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=50, num_outputs=3)  # 입력 특성 50개, 클래스 3개인 모델 생성
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


- 정방향 계산에서 신경망 사용
   - 50개의 특성을 가진 입력을 주입하고 3개의 클래스에 대한 출력 로짓을 얻는다
   - 정방향 계산은 입력 텐서로부터 출력 텐서를 계산하는 것을 의미한다.
   - 반환된 3개의 숫자는 3개의 출력노드에 할당된 점수이다.
   - 출력 텐서에 표시된 grad_fn=<AddmmBackward0>은 계산 그래프에서 변수를 계산하는데 마지막에 사용된 함수를 나타낸다.
      -  <AddmmBackward0>는 텐서가 행렬 곱셈과 덧셈 연산을 통해 만들어 졌다는 것을 의미한다.
         - Addmm는 행렬 곱셈(mm:matrix multiplication)과 덧셈(Add:addition)을 결합한 연산을 나타낸다.
      - 파이토치는 역전파 과정에서 그레이디언트를 계산할 때 이 정보를 사용한다.

In [18]:
torch.manual_seed(123)
X = torch.rand(1, 50)  # 배치 크기 1, 특성 개수 50인 무작위 입력 텐서 생성
out = model(X)  # 신경망에 입력 텐서 전달하여 정방향 계산 수행
print(out)  # 출력 로짓 텐서 출력

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


-  훈련이나 역전파 없이 신경망을 사용하기만 한다면(훈련이 끝난 후 예측 시) 이런 구성을 하는 것은 추가 자원을 소모하기 때문에 권장되지 않는다.
   - torch.no_grad() 컨텍스트 매니저를 사용해 불필요한 계산 그래프 생성을 방지할 수 있다.

In [19]:
with torch.no_grad():
    out = model(X)

print(out)  # 출력 로짓 텐서 출력

tensor([[-0.1262,  0.1080, -0.1792]])


   - 파이토치에서는 모델의 마지막 층의 출력(로짓)을 비선형 활성화 함수에 통과시키지 않고 출력하는 것이 일반적이다.
      - 이는 파이토치에서 널리 사용되는 손실 함수가 softmax(이진 분류일 경우 sigmoid) 연산과 음의 로그 가능도 손실을 하나의 클래스로 결합하고 있기 때문이다.
        - 예를 들어, nn.CrossEntropyLoss 손실 함수는 내부적으로 소프트맥스 연산을 수행하므로 모델의 출력에 소프트맥스를 적용할 필요가 없다.
      - 모델의 예측에 대한 클래스 소속 확률을 얻고 싶다면 명시적으로 softmax 연산을 적용해야 한다.

In [ ]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)

# 훈련하지 않고 랜덤하게 초기화된 모델이므로 클래스의 확률이 거의 비슷하다.
print(out)  # 출력 확률 텐서 출력

tensor([[0.3113, 0.3934, 0.2952]])
